### ISSUE TITLE
Fix: Ignore db.sqlite3

### ISSUE THREAD

**Issue by gray-adeyi** [kausaratg/customers_app#1]
Hello fellow django dev! found my way to your repo and i noticed you've also commited your database to your project.

**Comment by kausaratg** [comment]
> Hello fellow django dev! found my way to your repo and i noticed you've also commited your database to your project.



> Hello fellow django dev! found my way to your repo and i noticed you've also commited your database to your project.

Hello I am newbie django developer.. I am basically following a tutorial for now. And i don't know it is necessary not to commit my database. Thanks for the information.. i will work on that.

**Comment by gray-adeyi** [comment]
No wahala. Nobody knows all I understand. You can find django projects in my repo if you want

**Comment by kausaratg** [comment]
I will check it. Thank you

**Comment by gray-adeyi** [comment]
Don't hesitate to reach out. I'll be happy to help
